version: "3.1"
services:
  kavanest-api:
    container_name: kavanest-api
    image: kavanest-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    ports:
      - 4000:4000
    environment:
      - MQTT=mqtt://mosquitto
      - MONGO=mongodb://kavanest-mongo:27017

networks:
  proxynet:
    name: kavanest-devnet
