version: "3.1"
services:
  kavanest-api:
    container_name: kavanest-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - URI=mongodb://kavanest-mongo:27017/devices
    ports:
      - 4000:4000

networks:
  proxynet:
    name: kavanest-devnet
