name: kavanest-api

namespace: kavanest
env:
  APP_VERSION: d59a83fff730ba92aeb68d62e038b6b402994aad

deployment:
  - name: kavanest-api
    image: invisibug/kavanest-api
    ports:
    - port: 4000
    env:
    - name: MONGO
      value: mongodb://kavanest-mongo:27017

    - name: MQTT
      value: mqtt://mqtt.kavanet.io

    # - name: NODE_ENV
    #   value: production

ingress:
  - name: api.kavanet.io
    selector: kavanest-api
    path: /
    port: 4000
    host: api.kavanet.io

service:
  loadBalancer:
    - name: kavanest-api
      selector: kavanest-api
      port: 80
      containerPort: 4000
