name: kavanest-api

namespace: kavanest
env:
  APP_VERSION: cd1c7ef77ac99857172a7fee5f3ac3d903c66f37

deployment:
  - name: kavanest-api
    image: 192.168.1.61:5000/kavanest-api
    ports:
    - port: 4000
    env:
    - name: MONGO
      value: mongodb://kavanest-mongo:27017

    - name: MQTT
      value: mqtt://mqtt.kavanet.io

    # - name: NODE_ENV
    #   value: production

ingress:
  - name: api.kavanet.io
    selector: kavanest-api
    path: /
    port: 4000
    host: api.kavanet.io

service:
  loadBalancer:
    - name: kavanest-api
      selector: kavanest-api
      port: 80
      containerPort: 4000
