name: kavanest-test-api

namespace: kavanest-test

deployment:
  - name: kavanest-api
    image: 192.168.1.61:5000/kavanest-api
    ports:
    - port: 4000
    env:
    - name: ENVIRONMENT
      value: test

    - name: MONGO_TEST
      value: mongodb://kavanest-test-mongo:27017

    - name: MQTT_TEST
      value: mqtt://kavanest-simulator

ingress:
  - name: test.api.kavanet.io
    selector: kavanest-api
    path: /
    port: 4000
    host: test.api.kavanet.io

service:
  loadBalancer:
    - name: kavanest-api
      selector: kavanest-api
      port: 80
      containerPort: 4000
