name: kavanest-test-api

namespace: kavanest-test
env:
  APP_VERSION: ac2f344baab8955b12ec6c5073c1181d47d11f8f

deployment:
  - name: kavanest-test-api
    image: invisibug/kavanest-api
    ports:
    - port: 4000
    env:
    - name: MONGO
      value: mongodb://kavanest-test-mongo:27017

    - name: MQTT
      value: mqtt://kavanest-test-mqtt

ingress:
  - name: test.api.kavanet.io
    selector: kavanest-test-api
    path: /
    port: 4000
    host: test.api.kavanet.io

service:
  loadBalancer:
    - name: kavanest-test-api
      selector: kavanest-test-api
      port: 80
      containerPort: 4000
